import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-101: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short101', durationInSeconds: 35.0, fps: 30, width: 1080, height: 1920 };

const B1 = secToFrame(5.306);
const B2 = secToFrame(14.803);
const B3 = secToFrame(20.608);
const CTA = secToFrame(30.778);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short101: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-101/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="MICROSOFT MAI-TRANSCRIBE-2" lines={[{ text: '54 CENTS' }, { text: 'AN HOUR', accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="MAI-Transcribe-2-Streaming" tagline="Live speech-to-text, priced per audio hour." chip="INTRO PRICE" at={B1 + 4}>
          <Panel>
            <Line k="per audio hour" v="$0.54" good />
            <Line k="per 1,000 min" v="~$9" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="Built for live" tagline="Number one on Artificial Analysis." chip="60 LANGUAGES" at={B2 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="languages" v="60" good />
            <Line k="first words" v="~100 ms" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The catch" tagline="Introductory, through end of year." chip="READ THIS" at={B3 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="price after 2026" v="not stated" bad />
            <Line k="intro ends" v="Dec 31" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-101/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="MICROSOFT MAI-TRANSCRIBE-2" lines={[{ text: '54 CENTS' }, { text: 'AN HOUR', accent: true }]} />
      </AbsoluteFill>
      <CaptionTrack words={WORDS} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short101;
