import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-104: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short104', durationInSeconds: 30.5, fps: 30, width: 1080, height: 1920 };


const B1 = secToFrame(5.0);
const B2 = secToFrame(8.4);
const B3 = secToFrame(16.0);
const B4 = secToFrame(22.0);
const CTA = secToFrame(27.5);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short104: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-104/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="VOICE AI PRICING" lines={[{ text: 'MICROSOFT $15' }, { text: 'ELEVENLABS $40', accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="MAI-Voice-2.1-Flash" tagline="Microsoft's new voice model." chip="$15 / M" at={B1 + 4}>
          <Panel>
            <Line k="price / M chars" v="$15" good />
            <Line k="languages" v="23" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="ElevenLabs Flash API" tagline="$0.04 per 1,000 characters." chip="$40 / M" at={B2 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="price / M chars" v="$40" bad />
            <Line k="vs Microsoft" v="2.7x" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B4}>
        <ToolCard name="The specs" tagline="Microsoft's own figures." chip="45 MS" at={B3 + 4}>
          <Panel>
            <Line k="model latency" v="~45 ms" good />
            <Line k="languages" v="23" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The gap" tagline="The bigger MAI model is $22." chip="VERDICT" at={B4 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="MAI-Voice-2.1-Flash" v="$15" good />
            <Line k="MAI-Voice-2.1" v="$22" />
            <Line k="ElevenLabs Flash" v="$40" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-104/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="VOICE AI PRICING" lines={[{ text: 'MICROSOFT $15' }, { text: 'ELEVENLABS $40', accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Check the price per million.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short104;
