import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-104: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short104', durationInSeconds: 31.2, fps: 30, width: 1080, height: 1920 };

const B1 = secToFrame(3.4);
const B2 = secToFrame(11.0);
const B3 = secToFrame(19.2);
const CTA = secToFrame(26.8);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short104: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-104/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="GEMINI 3.8 FLASH" lines={[{ text: "FLASH PRICE" }, { text: "DOUBLES JAN 1", accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="Gemini 3.8 Flash" tagline="Through December 31." chip="NOW" at={B1 + 4}>
          <Panel>
            <Line k="input / M tokens" v="$0.75" good />
            <Line k="output / M tokens" v="$3.75" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="January 1, 2027" tagline="Both prices double." chip="2X" at={B2 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="input / M tokens" v="$1.50" bad />
            <Line k="output / M tokens" v="$7.50" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="Free tier" tagline="Prototype at zero." chip="FREE" at={B3 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="prototyping" v="$0" good />
            <Line k="shipping on Flash" v="budget 2x" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-104/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="GEMINI 3.8 FLASH" lines={[{ text: "FLASH PRICE" }, { text: "DOUBLES JAN 1", accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Cheap until New Year's.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS.filter((w) => w.end_s * 30 < CTA + 6)} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short104;
