import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-105: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short105', durationInSeconds: 39.3, fps: 30, width: 1080, height: 1920 };

const B1 = secToFrame(3.25);
const B2 = secToFrame(12.5);
const B3 = secToFrame(16.9);
const B4 = secToFrame(26.1);
const CTA = secToFrame(36.4);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short105: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-105/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="AI CODING PLANS" lines={[{ text: "CURSOR $20" }, { text: "COPILOT $10", accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="Copilot Pro" tagline="Unlimited completions." chip="$10/MO" at={B1 + 4}>
          <Panel>
            <Line k="price" v="$10/mo" good />
            <Line k="completions" v="unlimited" />
            <Line k="AI credits" v="$15/mo" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="Cursor Individual" tagline="Extended agent limits." chip="$20/MO" at={B2 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="price" v="$20/mo" />
            <Line k="agent limits" v="extended" />
            <Line k="$ amount listed" v="none" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B4}>
        <ToolCard name="Free tiers" tagline="Both let you start at zero." chip="FREE" at={B3 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="Copilot Free" v="2,000 completions" good />
            <Line k="Copilot Free chat" v="50 requests" />
            <Line k="Cursor Hobby" v="no card" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The gap" tagline="Autocomplete-heavy? Copilot." chip="VERDICT" at={B4 + 4}>
          <Panel>
            <Line k="Copilot Pro" v="$10/mo" good />
            <Line k="Cursor Individual" v="$20/mo" />
            <Line k="gap" v="$10/mo" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-105/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="AI CODING PLANS" lines={[{ text: "CURSOR $20" }, { text: "COPILOT $10", accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Ten dollars a month.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS.filter((w) => w.end_s * 30 < CTA + 6)} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short105;
