import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-105: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short105', durationInSeconds: 36.9, fps: 30, width: 1080, height: 1920 };


const B1 = secToFrame(3.5);
const B2 = secToFrame(13.0);
const B3 = secToFrame(19.2);
const B4 = secToFrame(24.9);
const CTA = secToFrame(33.0);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);


const Short105: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-105/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="NANO BANANA 2.1" lines={[{ text: '3 CENTS' }, { text: 'A PICTURE', accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="Nano Banana 2.1" tagline="Google's new image model, GA Oct 6." chip="$0.034 / 1K" at={B1 + 4}>
          <Panel>
            <Line k="1K image" v="$0.034" good />
            <Line k="2K image" v="$0.050" good />
            <Line k="4K image" v="$0.113" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="Nano Banana 2" tagline="The old price. Twice as much." chip="2x MORE" at={B2 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="1K image" v="$0.067" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B4}>
        <ToolCard name="Nano Banana Pro" tagline="Four times the price." chip="4x MORE" at={B3 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="1K / 2K image" v="$0.134" bad />
            <Line k="4K image" v="$0.240" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The catch" tagline="No free tier on the API." chip="NO FREE" at={B4 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="free tier" v="none" bad />
            <Line k="batch, 1K image" v="$0.017" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-105/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="NANO BANANA 2.1" lines={[{ text: '3 CENTS' }, { text: 'A PICTURE', accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Three cents a picture.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short105;
