import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-106: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short106', durationInSeconds: 34.9, fps: 30, width: 1080, height: 1920 };

const B1 = secToFrame(3.5);
const B2 = secToFrame(13.2);
const B3 = secToFrame(22.5);
const CTA = secToFrame(30.0);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short106: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-106/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="AI TESTING AGENT" lines={[{ text: "KANE CLI" }, { text: "FREE TESTING", accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="Kane CLI" tagline="Plain English to real Chrome." chip="TESTMU AI" at={B1 + 4}>
          <Panel>
            <Line k="you write" v="verify checkout flow" />
            <Line k="it returns" v="pass / fail" good />
            <Line k="plus" v="evidence pack" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="Pricing" tagline="CLI is free to install and use." chip="$0 LOCAL" at={B2 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="install" v="free" good />
            <Line k="local runs" v="$0" good />
            <Line k="cloud runs" v="billed to plan" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The promo" tagline="A free tester on your laptop." chip="PROMO" at={B3 + 4}>
          <Panel>
            <Line k="Kane credits" v="10,000" good />
            <Line k="for" v="one month" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-106/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="AI TESTING AGENT" lines={[{ text: "KANE CLI" }, { text: "FREE TESTING", accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Plain English tests, free.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS.filter((w) => w.end_s * 30 < CTA + 6)} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short106;
