import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-106: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short106', durationInSeconds: 31.9, fps: 30, width: 1080, height: 1920 };


const B1 = secToFrame(3.1);
const B2 = secToFrame(7.0);
const B3 = secToFrame(11.5);
const B4 = secToFrame(17.5);
const B5 = secToFrame(19.8);
const CTA = secToFrame(27.9);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);


const Short106: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-106/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="VEO 3.1 LITE" lines={[{ text: '5 CENTS' }, { text: 'A SECOND', accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="Veo 3.1 Lite" tagline="Google's cheapest AI video." chip="$0.05 / SEC" at={B1 + 4}>
          <Panel>
            <Line k="720p" v="$0.05 / s" good />
            <Line k="1080p" v="$0.08 / s" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="Veo 3.1 Standard" tagline="Eight times the price." chip="8x MORE" at={B2 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="720p / 1080p" v="$0.40 / s" bad />
            <Line k="4K" v="$0.60 / s" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B4}>
        <ToolCard name="An 8-second clip" tagline="Same length, very different bill." chip="MATH" at={B3 + 4}>
          <Panel>
            <Line k="on Lite" v="$0.40" good />
            <Line k="on Standard" v="$3.20" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B5}>
        <ToolCard name="Veo 3.1 Fast" tagline="The middle option." chip="$0.10 / SEC" at={B4 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="720p" v="$0.10 / s" />
            <Line k="1080p" v="$0.12 / s" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The catch" tagline="Lite stops at 1080p." chip="NO 4K" at={B5 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="max resolution" v="1080p" bad />
            <Line k="1080p price" v="$0.08 / s" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-106/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="VEO 3.1 LITE" lines={[{ text: '5 CENTS' }, { text: 'A SECOND', accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Five cents a second.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short106;
