import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-107: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short107', durationInSeconds: 34.8, fps: 30, width: 1080, height: 1920 };

const B1 = secToFrame(4.4);
const B2 = secToFrame(8.0);
const B3 = secToFrame(13.0);
const B4 = secToFrame(16.0);
const B5 = secToFrame(21.0);
const CTA = secToFrame(29.8);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short107: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  const hook = <HookTitle hold onDark kicker="AI IMAGE PRICING" lines={[{ text: 'FLUX 4K: 61¢' }, { text: 'GOOGLE 4K: 11¢', accent: true }]} />;
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-107/cover.png" out={B1 - 10} />
        {hook}
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="FLUX 3 Image" tagline="Black Forest Labs, 4K." chip="$0.607" at={B1 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="4K / image" v="$0.607" bad />
            <Line k="2K / image" v="$0.100" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="Nano Banana 2.1" tagline="Google, same 4K size." chip="$0.113" at={B2 + 4}>
          <Panel>
            <Line k="4K / image" v="$0.113" good />
            <Line k="2K / image" v="$0.0504" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B4}>
        <ToolCard name="The gap" tagline="4K price, FLUX vs Google." chip="5.4x" at={B3 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="FLUX 4K" v="$0.607" bad />
            <Line k="Google 4K" v="$0.113" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B5}>
        <ToolCard name="At 1K" tagline="Closer, still Google." chip="1K" at={B4 + 4}>
          <Panel>
            <Line k="FLUX 1K" v="$0.048" />
            <Line k="Google 1K" v="$0.0336" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="FLUX small size" tagline="768 px square." chip="$0.041" at={B5 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="768sq / image" v="$0.041" good />
            <Line k="4K / image" v="$0.607" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-107/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="AI IMAGE PRICING" lines={[{ text: 'FLUX 4K: 61¢' }, { text: 'GOOGLE 4K: 11¢', accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Check the resolution first.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short107;
