import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-103: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short103', durationInSeconds: 35.1, fps: 30, width: 1080, height: 1920 };


const B1 = secToFrame(4.9);
const B2 = secToFrame(7.4);
const B3 = secToFrame(17.0);
const B4 = secToFrame(25.5);
const CTA = secToFrame(30.4);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short103: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-103/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="CLAUDE HAIKU 5.5" lines={[{ text: '10 CENTS' }, { text: 'PER MILLION', accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="Claude Haiku 5.5" tagline="Anthropic's cheapest model yet." chip="$0.10 IN" at={B1 + 4}>
          <Panel>
            <Line k="input / M tokens" v="$0.10" good />
            <Line k="output / M tokens" v="$0.50" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="Haiku 4.5" tagline="The old price. Ten times higher." chip="10x MORE" at={B2 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="input / M tokens" v="$1.00" bad />
            <Line k="output / M tokens" v="$5.00" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B4}>
        <ToolCard name="The catch" tagline="Prompts over 100k tokens cost 5x." chip="OVER 100K" at={B3 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="input / M tokens" v="$0.50" />
            <Line k="output / M tokens" v="$2.50" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The math" tagline="Keep prompts short, pay a dime." chip="VERDICT" at={B4 + 4}>
          <Panel>
            <Line k="under 100k, input" v="$0.10" good />
            <Line k="under 100k, output" v="$0.50" good />
            <Line k="over 100k, input" v="$0.50" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-103/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="CLAUDE HAIKU 5.5" lines={[{ text: '10 CENTS' }, { text: 'PER MILLION', accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          A million tokens for a dime.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short103;
