import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-102: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short102', durationInSeconds: 34.0, fps: 30, width: 1080, height: 1920 };

const B1 = secToFrame(3.843);
const B2 = secToFrame(8.95);
const B3 = secToFrame(12.69);
const B4 = secToFrame(19.597);
const CTA = secToFrame(29.501);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short102: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-102/cover.png" out={B1 - 10} />
        <HookTitle hold onDark kicker="AI VIDEO LICENSING" lines={[{ text: 'PIKA $10 PLAN' }, { text: 'NO LICENSE', accent: true }]} />
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="Pika Starter" tagline="$10/mo, 900 credits." chip="NO LICENSE" at={B1 + 4} chipColor={COLORS.danger}>
          <Panel>
            <Line k="price" v="$10/mo" />
            <Line k="commercial license" v="none" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="Pika Creator" tagline="The tier that adds commercial use." chip="$35/MO" at={B2 + 4}>
          <Panel>
            <Line k="price" v="$35/mo" />
            <Line k="commercial license" v="included" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B4}>
        <ToolCard name="Luma Plus" tagline="10,000 credits a month." chip="$30/MO" at={B3 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="price" v="$30/mo" good />
            <Line k="commercial use" v="every plan" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The math" tagline="Selling AI video? Luma is $5 cheaper." chip="VERDICT" at={B4 + 4}>
          <Panel>
            <Line k="Luma Plus" v="$30/mo" good />
            <Line k="Pika Creator" v="$35/mo" />
            <Line k="Pika Free" v="0 credits" bad />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-102/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="AI VIDEO LICENSING" lines={[{ text: 'PIKA $10 PLAN' }, { text: 'NO LICENSE', accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Read the license, not the price.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short102;
