import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame } from 'remotion';
import { COLORS, EASINGS } from '../../brand';
import { FONT_BODY, FONT_MONO } from '../../fonts';
import { CLAMP } from '../../lib/kit';
import { CaptionTrack, CoverImage, HookTitle, ProgressBar, SAFE, ShortBg, ToolCard, Watermark, secToFrame } from '../../lib/shorts';
import { WORDS } from './words';

// short-108: generated by the daily batch. Cover held at frame 0; closes on the cover.
export const compositionConfig = { id: 'Short108', durationInSeconds: 31.8, fps: 30, width: 1080, height: 1920 };

const B1 = secToFrame(5.0);
const B2 = secToFrame(8.2);
const B3 = secToFrame(17.0);
const B4 = secToFrame(21.2);
const CTA = secToFrame(25.4);

const FadeOut: React.FC<{ at: number; children: React.ReactNode }> = ({ at, children }) => {
  const frame = useCurrentFrame();
  const op = 1 - interpolate(frame, [at - 8, at + 2], [0, 1], { ...CLAMP, easing: EASINGS.easeIn });
  return <AbsoluteFill style={{ opacity: op }}>{children}</AbsoluteFill>;
};

const Line: React.FC<{ k: string; v: string; good?: boolean; bad?: boolean }> = ({ k, v, good, bad }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', fontFamily: FONT_MONO, fontSize: 32 }}>
    <span style={{ color: COLORS.d400 }}>{k}</span>
    <span style={{ color: bad ? COLORS.danger : good ? COLORS.signalAlt : COLORS.d300, fontWeight: good || bad ? 700 : 400 }}>{v}</span>
  </div>
);
const Panel: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div style={{ background: COLORS.d900, borderRadius: 12, padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 16 }}>{children}</div>
);

const Short108: React.FC = () => {
  const frame = useCurrentFrame();
  const ctaOp = interpolate(frame, [CTA, CTA + 12], [0, 1], { ...CLAMP, easing: EASINGS.easeOut });
  const hook = <HookTitle hold onDark kicker="PERPLEXITY API" lines={[{ text: '2¢ PER MILLION' }, { text: 'OUTPUT FREE', accent: true }]} />;
  return (
    <AbsoluteFill>
      <ShortBg />
      <FadeOut at={B1}>
        <CoverImage src="projects/short-108/cover.png" out={B1 - 10} />
        {hook}
      </FadeOut>
      <FadeOut at={B2}>
        <ToolCard name="Decisions API" tagline="Perplexity's pricing page." chip="2¢ / M" at={B1 + 4}>
          <Panel>
            <Line k="input / M tokens" v="$0.02" good />
            <Line k="output / M tokens" v="free" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B3}>
        <ToolCard name="What it returns" tagline="Probabilities, not prose." chip="YES / NO" at={B2 + 4}>
          <Panel>
            <Line k="yes / no" v="probability" />
            <Line k="pick an option" v="probability" />
            <Line k="rubric level" v="probability" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={B4}>
        <ToolCard name="Use cases" tagline="Think spam, routing, moderation." chip="SORT" at={B3 + 4}>
          <Panel>
            <Line k="per request fee" v="none" good />
            <Line k="models" v="2" />
          </Panel>
        </ToolCard>
      </FadeOut>
      <FadeOut at={CTA}>
        <ToolCard name="The bill" tagline="Output tokens cost nothing." chip="$0" at={B4 + 4} chipColor={COLORS.accent2}>
          <Panel>
            <Line k="input / M tokens" v="$0.02" good />
            <Line k="output / M tokens" v="$0.00" good />
          </Panel>
        </ToolCard>
      </FadeOut>
      <AbsoluteFill style={{ opacity: ctaOp }}>
        <CoverImage src="projects/short-108/cover.png" at={CTA} />
        <HookTitle hold onDark at={CTA} kicker="PERPLEXITY API" lines={[{ text: '2¢ PER MILLION' }, { text: 'OUTPUT FREE', accent: true }]} />
        <div style={{ position: 'absolute', left: SAFE.side, right: SAFE.side, top: SAFE.top + 520, textAlign: 'center', fontFamily: FONT_BODY, fontWeight: 600, fontSize: 44, color: 'rgba(255,255,255,0.82)' }}>
          Two cents per million.
        </div>
      </AbsoluteFill>
      <CaptionTrack words={WORDS} />
      <Watermark at={12} />
      <ProgressBar />
    </AbsoluteFill>
  );
};
export default Short108;
